export type WeaponItem = {
    Name: string;
    Unique: boolean;
    Hund: boolean;
    Maker: string;
    "Weapon Type": string;
    Stun: boolean;
    Power: number;
    Penetration: number;
    Acc: number;
    Ammo: number;
    "Ammo Type": string;
    Range: number;
    AP: number;
    Speed: number;
    Price: number;
    "MnB only": boolean;
    Source: string;
    Zone: string;
    "Zone Faction": string;
    "Shop Order": number;
    "Total Damage": number;
    "Damage Per AP": number;
    "¥/Dam Per AP": number;
    "TD * Accuracy": number;
    "Power Ratio": number;
    "shots in full round": number;
    "(power + pen) * shots": number;
  };